### PR TITLE
Improves build script

### PR DESCRIPTION
**Pull request by mzorec**

### CODE REVIEW

**Comment by catcherwong** [comment]
It seems that `dotnet test` failed only in **Ubuntu1804**

image

image

**Comment by mzorec** [comment]
Yes. I've noticed. That's why i added [WIP] which means work in progress. It looks like i have made a bug in FlubuCore 5.0.2.

**Comment by mzorec** [comment]
I have fixed the issue.

**Comment by catcherwong** [comment]
Thank you!!! 😄

**Pull request merged**
