### PR TITLE
Fix   LiteDB  cache expiration issue.  #248

### LINKED ISSUE #248: LiteDB调用Get获取缓存缺少超时控制
LiteDB调用Get获取缓存缺少超时控制

### PR DESCRIPTION
**Pull request by maikebing**
Fix   LiteDB  cache expiration issue.  #248

### CODE REVIEW

**Comment by maikebing** [comment]
@lable  @catcherwong   The PR is ready.

**Comment by catcherwong** [comment]
There are two unit tests did not pass yet. 

image

- TrySet_Value_And_Get_Cached_Value_Should_Succeed
- TrySet_Value_And_Get_Cached_Value_Async_Should_Succeed



BTW, the base branch should be `dev`.

**Comment by maikebing** [comment]
LGFM

**Review by catcherwong — APPROVED** [review]
LGTM

**Pull request merged**
