### PR TITLE
add `persist` key method to redis providers

### PR DESCRIPTION
**Pull request by MoienTajik**
Added "[Persist](https://redis.io/commands/persist/)" operation in Redis providers + related test.

### CODE REVIEW

**Review by catcherwong — APPROVED** [review]
LGTM

**Comment by MoienTajik** [comment]
Thanks, 
As we need this in our application, when this would be released on NuGet?

@catcherwong

**Comment by catcherwong** [comment]
Released v1.6.1 on NuGet.

**Comment by MoienTajik** [comment]
> Released v1.6.1 on NuGet.

Thanks.

**Pull request merged**
