### PR TITLE
fix: Using IConfiguration for WithRedisBus configuration cause DefaultRedisBus throw "Sequence contains no matching element" exception

### LINKED ISSUE #477: Using IConfiguration for WithRedisBus configuration cause DefaultRedisBus throw "Sequence contains no matching element" exception
## Description

Using `IConfiguration` for `WithRedisBus` configuration cause `DefaultRedisBus` throw **"Sequence contains no matching element"** exception.

### Error log

<details>
<summary>Click to expand</summary>

```txt
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at EasyCaching.Bus.Redis.DefaultRedisBus..ctor(String name, IEnumerable`1 subscriberProviders, RedisBusOptions busOptions, IEnumerable`1 serializers)
   at EasyCaching.Bus.Redis.RedisBusOptionsExtension.<AddServices>b__3_1(IServiceProvider x)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.HybridCacheOptionsExtension.<AddServices>b__3_0(IServiceProvider x)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
```
</details>

### Steps to Reproduce

Please see `Related code`

### Related code

```csharp
services.AddEasyCaching(option =>
{
    option
        .UseInMemory(configuration, name: "InMemoryCache")
        .UseRedis(configuration, name: "RedisCache")
        .UseHybrid(configuration, name: "HybridCache")
        .WithRedisBus(configuration, name: "RedisBus")
        .WithMessagePack(x =>
        {
          x.EnableCustomResolver = true;
          x.CustomResolvers = CompositeResolver.Create(new MessagePack.IFormatterResolver[]
          {
            // This can solve DateTime time zone problem
            NativeDateTimeResolver.Instance,
            ContractlessStandardResolver.Instance
          });
        }, "RemoteCacheSerializer");
});
```

**Expected behavior:** Redis bus is configured using `IConfiguration` and working properly.

**Actual behavior:** `DefaultRedisBus` throw **"Sequence contains no matching element"** exception.

## Specifications

- Bus    : **EasyCaching.Bus.Redis** (version `1.9.0`)
- Serializer  : **EasyCaching.Serialization.MessagePack** (version `1.9.0`)
- System      : `Windows 10` `Professional` `22H2` `19045.3086`

### PR DESCRIPTION
**Pull request by billhong-just**
Fixes #477

### CODE REVIEW

**Review by catcherwong — APPROVED** [review]
LGTM

**Comment by billhong-just** [comment]
Sure, like this?

### EasyCaching/build/version.props

```xml
<Project>
	<PropertyGroup>
		<EasyCachingCorePackageVersion>1.9.0</EasyCachingCorePackageVersion>
		<EasyCachingMemcachedPackageVersion>1.9.0</EasyCachingMemcachedPackageVersion>
		<EasyCachingRedisPackageVersion>1.9.0</EasyCachingRedisPackageVersion>
		<EasyCachingSQLitePackageVersion>1.9.0</EasyCachingSQLitePackageVersion>
		<EasyCachingInMemoryPackageVersion>1.9.0</EasyCachingInMemoryPackageVersion>
		<EasyCachingHybridPackageVersion>1.9.0</EasyCachingHybridPackageVersion>
		<EasyCachingAspectCorePackageVersion>1.9.0</EasyCachingAspectCorePackageVersion>
		<EasyCachingCastlePackageVersion>1.9.0</EasyCachingCastlePackageVersion>
		<EasyCachingResponseCachingPackageVersion>1.9.0</EasyCachingResponseCachingPackageVersion>
		<EasyCachingJsonPackageVersion>1.9.0</EasyCachingJsonPackageVersion>
		<EasyCachingMessagePackPackageVersion>1.9.0</EasyCachingMessagePackPackageVersion>
		<EasyCachingProtobufPackageVersion>1.9.0</EasyCachingProtobufPackageVersion>
		<EasyCachingCSRedisPackageVersion>1.9.0</EasyCachingCSRedisPackageVersion>
		<EasyCachingRedisBusPackageVersion>1.9.1</EasyCachingRedisBusPackageVersion>
		<EasyCachingCSRedisBusPackageVersion>1.9.0</EasyCachingCSRedisBusPackageVersion>
		<EasyCachingRabbitBusPackageVersion>1.9.0</EasyCachingRabbitBusPackageVersion>
		<EasyCachingKafkaBusPackageVersion>1.9.0</EasyCachingKafkaBusPackageVersion>
		<EasyCachingZookeeperBusPackageVersion>1.9.0</EasyCachingZookeeperBusPackageVersion>
		<EasyCachingDiskPackageVersion>1.9.0</EasyCachingDiskPackageVersion>
		<EasyCachingMsExtPackageVersion>1.9.0</EasyCachingMsExtPackageVersion>
		<EasyCachingLiteDBPackageVersion>1.9.0</EasyCachingLiteDBPackageVersion>
		<EasyCachingSTJsonPackageVersion>1.9.0</EasyCachingSTJsonPackageVersion>
		<EasyCachingMemoryPackageVersion>1.9.0</EasyCachingMemoryPackageVersion>
		<EasyCachingFaskKVPackageVersion>1.9.0</EasyCachingFaskKVPackageVersion>
	</PropertyGroup>
</Project>
```

### EasyCaching/build/releasenotes.props

```xml
<Project>
	<PropertyGroup>
		<EasyCachingCorePackageNotes>
		</EasyCachingCorePackageNotes>
		<EasyCachingMemcachedPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingMemcachedPackageNotes>
		<EasyCachingRedisPackageNotes>
			1. Fixed redis distributed lock for different process.
			2. Support code configuration for StackExchange.Redis.
		</EasyCachingRedisPackageNotes>
		<EasyCachingSQLitePackageNotes>
			1. Upgrading dependencies.
		</EasyCachingSQLitePackageNotes>
		<EasyCachingInMemoryPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingInMemoryPackageNotes>
		<EasyCachingHybridPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingHybridPackageNotes>
		<EasyCachingAspectCorePackageNotes>
			1. Upgrading dependencies.
		</EasyCachingAspectCorePackageNotes>
		<EasyCachingCastlePackageNotes>
			1. Upgrading dependencies.
		</EasyCachingCastlePackageNotes>
		<EasyCachingResponseCachingPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingResponseCachingPackageNotes>
		<EasyCachingJsonPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingJsonPackageNotes>
		<EasyCachingMessagePackPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingMessagePackPackageNotes>
		<EasyCachingProtobufPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingProtobufPackageNotes>
		<EasyCachingCSRedisPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingCSRedisPackageNotes>
		<EasyCachingCSRedisBusPackageNotes>
			1. Support async version of subscribe.
		</EasyCachingCSRedisBusPackageNotes>
		<EasyCachingRedisBusPackageNotes>
			1. Support code configuration for StackExchange.Redis.
			2. Support async version of subscribe.
			3. fix: Using IConfiguration for WithRedisBus configuration cause DefaultRedisBus throw "Sequence contains no matching element" exception
		</EasyCachingRedisBusPackageNotes>
		<EasyCachingRabbitBusPackageNotes>
			1. Support async version of subscribe.
		</EasyCachingRabbitBusPackageNotes>
		<EasyCachingKafkaBusPackageNotes>
			1. Support async version of subscribe.
		</EasyCachingKafkaBusPackageNotes>
		<EasyCachingZookeeperBusPackageNotes>
			1. Support async version of subscribe.
			2. Rename WithConfluentKafkaBus to WithZookeeeperBus.
		</EasyCachingZookeeperBusPackageNotes>
		<EasyCachingDiskPackageNotes>
			1. Support custom serializer.
			2. Fixed DiskCachingProvider async warning.
		</EasyCachingDiskPackageNotes>
		<EasyCachingLiteDBPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingLiteDBPackageNotes>
		<EasyCachingSTJsonPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingSTJsonPackageNotes>
		<EasyCachingMemoryPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingMemoryPackageNotes>
		<EasyCachingFaskKVPackageNotes>
			1. Upgrading dependencies.
		</EasyCachingFaskKVPackageNotes>
	</PropertyGroup>
</Project>
```

**Review by catcherwong — APPROVED** [review]

**Comment by billhong-just** [comment]
@catcherwong Hi, do you have a release schedule for **EasyCaching.Redis.Bus** `v1.9.1`?

**Comment by catcherwong** [comment]
https://www.nuget.org/packages/EasyCaching.Bus.Redis/1.9.1

**Comment by billhong-just** [comment]
@catcherwong Thank you so much.

**Pull request merged**
