### PR TITLE
Performance improvement of SearchRedisKeys method using Lua scripting

### PR DESCRIPTION
**Pull request by mjebrahimi**
This implementation has a huge performance benefit because of using Lua scripting if the server supports it. (Otherwise, it works the same way as before)

In my benchmark, it was **20 to 70 times faster** depending on the number of keys and the number of iteration.

### CODE REVIEW

**Comment by catcherwong** [comment]
@mjebrahimi Thanks for your interest in this project.

We should not use `KEYS` command in production environment! 

Most of time, we will add the following configuration in the redis config.

```
rename-command KEYS     ""
```

The `Keys` method of `StackExchange.Redis` will use `SCAN` method if redis server support this feature.

**Comment by mjebrahimi** [comment]
I know that but why The Keys method of StackExchange.Redis is 20-70x slower?
You can test it with a benchmark.

**Comment by mjebrahimi** [comment]
This benchmark show difference between using Lua script for GetCount key method or not using

**Result: using Lua scripts is 20-90x faster and 2-62x less allocation**

Untitled

Source code: https://github.com/mjebrahimi/EasyCaching/tree/redis-luakeys/test/LuaScript.Benchmark

In my opinion, adding this feature is very necessary and useful. We can add it in a settingable way
What do you think about it?

**Comment by catcherwong** [comment]
Sorry for the delay, I will take a look later this day.

**Comment by catcherwong** [comment]
When I tested your benchmark code. There are some different here.

With same redis endpoint, `with lua scripts` performances better than `without lua script`.

image

With different redis endpoints, `without lua scripts` performances better than `with lua script`.

image

**Comment by mjebrahimi** [comment]
You probably made a mistake because [here](https://github.com/mjebrahimi/EasyCaching/blob/redis-luakeys/test/LuaScript.Benchmark/GetCountBenchmark.cs#L61) the items are added on `RedisWithLua` but you've tested `RedisWithoutLua.GetCount()` on an empty database (with no records)

**Comment by catcherwong** [comment]
I use the following code.

```cs
        [GlobalSetup]
        public void Setup()
        {
            //  ...
            services.AddEasyCaching(opt =>
            {
                opt.UseRedis(config =>
                {
                    config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6380));
                    config.UseLuaScripts = true;
                }, "WithLua");

                opt.UseRedis(config =>
                {
                    config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6379));
                    config.UseLuaScripts = false;
                }, "WithoutLua");
            });

            var serviceProvider = services.BuildServiceProvider();
            var factory = serviceProvider.GetRequiredService<IEasyCachingProviderFactory>();

            RedisWithLua = factory.GetCachingProvider("WithLua");
            RedisWithoutLua = factory.GetCachingProvider("WithoutLua");

           // ....

            RedisWithLua.SetAll(dictonary, TimeSpan.FromMinutes(5));
            RedisWithoutLua.SetAll(dictonary, TimeSpan.FromMinutes(5));
        }

        [GlobalCleanup]
        public void Cleanup()
        {
            RedisWithLua.RemoveByPrefix(KeyPrefix);
            RedisWithoutLua.RemoveByPrefix(KeyPrefix);
        }
```

I find out the reason why `with lua` is  faster than `wihout lua`.

The default pageSize is **10**, when the redis server support `SCAN`, it will return 10 keys per times, if there are lots of keys can be matched, it will cost time here.

https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/Interfaces/IServer.cs#L374

I change this default pageSize from 10 to 100, 1000 and 5000.  

image

Here is the result.

## 100

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.16299.309 (1709/FallCreatorsUpdate/Redstone3)
Intel Xeon CPU E5-2680 v2 2.80GHz, 1 CPU, 20 logical and 10 physical cores
Frequency=2728175 Hz, Resolution=366.5454 ns, Timer=TSC
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT  [AttachedDebugger]
  Job-RZKRMV : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT

RunStrategy=Throughput  

```
|     Method |    Categories |      Mean |     Error |    StdDev |    Median | Ratio | RatioSD |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------- |-------------- |----------:|----------:|----------:|----------:|------:|--------:|--------:|-------:|------:|----------:|
|    WithLua |   CountOneKey |  1.327 ms | 0.0189 ms | 0.0176 ms |  1.322 ms |  1.00 |    0.00 |       - |      - |     - |    4.7 KB |
| WithoutLua |   CountOneKey | 24.238 ms | 0.4694 ms | 0.6425 ms | 24.187 ms | 18.29 |    0.62 |       - |      - |     - |   40.7 KB |
|            |               |           |           |           |           |       |         |         |        |       |           |
|    WithLua | CountManyKeys |  3.837 ms | 0.0749 ms | 0.1189 ms |  3.771 ms |  1.00 |    0.00 | 27.3438 | 7.8125 |     - | 338.89 KB |
| WithoutLua | CountManyKeys | 27.329 ms | 0.5400 ms | 0.6829 ms | 27.351 ms |  7.12 |    0.26 |       - |      - |     - | 361.58 KB |


## 1000

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.16299.309 (1709/FallCreatorsUpdate/Redstone3)
Intel Xeon CPU E5-2680 v2 2.80GHz, 1 CPU, 20 logical and 10 physical cores
Frequency=2728175 Hz, Resolution=366.5454 ns, Timer=TSC
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT  [AttachedDebugger]
  Job-AZPOAG : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT

RunStrategy=Throughput  

```
|     Method |    Categories |     Mean |     Error |    StdDev | Ratio | RatioSD |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------- |-------------- |---------:|----------:|----------:|------:|--------:|--------:|-------:|------:|----------:|
|    WithLua |   CountOneKey | 1.343 ms | 0.0215 ms | 0.0201 ms |  1.00 |    0.00 |       - |      - |     - |    4.7 KB |
| WithoutLua |   CountOneKey | 9.191 ms | 0.0770 ms | 0.0721 ms |  6.84 |    0.11 |       - |      - |     - |   8.48 KB |
|            |               |          |           |           |       |         |         |        |       |           |
|    WithLua | CountManyKeys | 3.787 ms | 0.0733 ms | 0.0814 ms |  1.00 |    0.00 | 27.3438 | 7.8125 |     - | 341.95 KB |
| WithoutLua | CountManyKeys | 9.998 ms | 0.1059 ms | 0.0991 ms |  2.63 |    0.06 | 15.6250 |      - |     - | 327.11 KB |


## 5000

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.16299.309 (1709/FallCreatorsUpdate/Redstone3)
Intel Xeon CPU E5-2680 v2 2.80GHz, 1 CPU, 20 logical and 10 physical cores
Frequency=2728175 Hz, Resolution=366.5454 ns, Timer=TSC
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT  [AttachedDebugger]
  Job-LXYPRR : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT

RunStrategy=Throughput  

```
|     Method |    Categories |     Mean |     Error |    StdDev | Ratio | RatioSD |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------- |-------------- |---------:|----------:|----------:|------:|--------:|--------:|-------:|------:|----------:|
|    WithLua |   CountOneKey | 1.324 ms | 0.0216 ms | 0.0202 ms |  1.00 |    0.00 |       - |      - |     - |    4.7 KB |
| WithoutLua |   CountOneKey | 6.566 ms | 0.1288 ms | 0.1265 ms |  4.97 |    0.14 |       - |      - |     - |   5.29 KB |
|            |               |          |           |           |       |         |         |        |       |           |
|    WithLua | CountManyKeys | 4.838 ms | 0.1069 ms | 0.1000 ms |  1.00 |    0.00 | 31.2500 | 7.8125 |     - | 429.98 KB |
| WithoutLua | CountManyKeys | 7.897 ms | 0.1488 ms | 0.1592 ms |  1.64 |    0.04 | 15.6250 |      - |     - | 341.76 KB |

So, I think that find out a suitable pageSize is more better than use command `KEYS` directly.

**Comment by mjebrahimi** [comment]
So it's not about different endpoints.
Therefore I changed codes a bit for testing several counting methods as below.

Untitled2

And that's the result:

Untitled

Although `LuaKeys` option is 1.5 to 4.3x faster than `KeysPageSize5000`, but I agree with you that find out a suitable pageSize is better.

But how do you want to find a suitable pageSize for all consumers? or probably made it settingable.

**Comment by catcherwong** [comment]
No, it will not be settingable here, because this is SE.Redis only, not suitable for other providers.

Maybe take a look on others' experience will help us to make a decision.

**Pull request merged**
