### PR TITLE
fix typo: IsHightAvailability -> IsHighAvailability

### PR DESCRIPTION
**Pull request by Rwing**
Maybe it's a breaking change?

### CODE REVIEW

**Comment by catcherwong** [comment]
@Rwing  LGTM, could you please change the target branch to dev?

**Comment by Rwing** [comment]
I have changed.

**Comment by catcherwong** [comment]
@Rwing  Merged! Thanks for your PR! 😄

**Comment by Rwing** [comment]
It's a breaking change, you'd better remind user.😄

**Pull request merged**
