### PR TITLE
Interceptor should generate valid cache key for basic type parameters

### PR DESCRIPTION
**Pull request by Powerz**
Interceptor respects only int, long, string, DateTime (in a weird way though), and ignores other primitive types e.g. Guid, decimal, DateTimeOffset etc.

Thus, if we cache a method with a guid parameter, we'll aways hit cache no matter what parameter is passed.

This PR changes DefaultEasyCachingKeyGenerator so that it respects simple types, arrays and types with proper ToString method.

### CODE REVIEW

**Comment by Powerz** [comment]
Hi @catcherwong ,

Could you please have a look at this PR?

**Comment by catcherwong** [comment]
@Powerz  This PR looks good for me!

Thank you vary much! 😄

**Comment by catcherwong** [comment]
And please change the target branch to `dev`.

**Comment by Powerz** [comment]
Hi @catcherwong , 

Thank you. I've created a new PR against dev and closing this one. Please take a look when you have some time. https://github.com/dotnetcore/EasyCaching/pull/88

**Pull request closed without merging**
