### PR TITLE
SQL Server provider

### PR DESCRIPTION
**Pull request by Wasenshi**
- Use SQL Server as a provider (Need SQL adjustment for MySQL or other SQL provider)
- Also scan and remove expired cache item(s)

Please add this provider to the official EasyCaching Repository and feel free to adjust anything as you deem fit.

### CODE REVIEW

**Comment by catcherwong** [comment]
@Wasenshi  Thanks for your interest in this project.

SQL Server is not suitable for a caching provider.

We only read the data from SQL Server, MySQL or others, and then store the data to cache. 

We will not use SQL Server as the cache layer!!

**Comment by Wasenshi** [comment]
> @Wasenshi Thanks for your interest in this project.
> 
> SQL Server is not suitable for a caching provider.
> 
> We only read the data from SQL Server, MySQL or others, and then store the data to cache.
> 
> We will not use SQL Server as the cache layer!!

Yes, I know. But I pull request this because I think it will be useful for others too.

This will be a good choice for developing phase. Where distributed cache is needed but the target deployment environment is not ready for distributed cache yet (servers are not yet set up, redis is in progress of set up, etc.)

proof me wrong but Microsoft also has DistributedCache with SQLServer implementation. That means even Microsoft sees some use or benefit in this. (https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#distributed-sql-server-cache)

**Comment by catcherwong** [comment]
> This will be a good choice for developing phase. Where distributed cache is needed but the target deployment environment is not ready for real distributed cache yet (servers are not yet set up, redis is in progress of set up, etc.)

Actually, EasyCaching only provides the caching providers for users, all the providers must implement `IEasyCachingProvider`  and it contains some basic APIs to handle caching which are no matter distributed cache or local cache. If we want to change the provider, what we need to do is just making some changes in the Startup class.

> proof me wrong but Microsoft also has DistributedCache with SQLServer implementation. That means even Microsoft sees some use or benefit in this. (https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#distributed-sql-server-cache)

You are right for the idea! 😄 

However, EasyCaching's original intention is an abstract caching provider layer! It will provides just some default implementation for some common caching components. Everyone can modify the default implementation or add some new providers by themselves. Not all providers' source code will store in only one repository, but both of them can be added a link in the README so that people can know there are some more providers. This may be more better.

**Comment by Wasenshi** [comment]
> Not all providers' source code will store in only one repository, but both of them can be added a link in the README so that people can know there are some more providers. This may be more better.

I see! I agree with that.

**Pull request closed without merging**
