### PR TITLE
Support removing cache keys by pattern

### LINKED ISSUE #399: Remove cache keys with key pattern
## Description

I have hybrid caching implemented on my system by using in-memory and redis provider, I want to be able to remove cache keys by a key pattern, for example, I have the following keys:

- configurations:games:ranks
- configurations:games:players

What I want to remove here is any key that includes `games`, so, I'd have a key pattern that looks like `*games*`

I tried to use `IHybridCachingProvider.RemoveAsync` which uses `unlink` command in redis, by using `*games*` as the key it would run the following command in redis that does not remove any keys:

```
unlink *games*
```

Then I wanted to try with `IHybridCachingProvider.RemoveByPrefixAsync` which uses `scan` to find the keys with the pattern that only ends with `*`, because it replaces the `*` in the pattern that I'm passing so `*games*` becomes `games*` that does not find the keys that I'm targetting.

```
scan 0 match games* count 200
```

https://github.com/dotnetcore/EasyCaching/blob/bac207ba604c75f5a9f9e687d07be2453cbf9ee7/src/EasyCaching.Redis/DefaultRedisCachingProvider.cs#L279

https://github.com/dotnetcore/EasyCaching/blob/bac207ba604c75f5a9f9e687d07be2453cbf9ee7/src/EasyCaching.Redis/DefaultRedisCachingProvider.cs#L341-L358

### Expected

The expected redis command that works for this issue is as following,

```
scan 0 match *games* count 200
```

The requirement here is to have a new method or any other solution to be able to remove keys by a pattern that is not limited by only a prefix. I'd be glad to contribute to this because it's a necessary feature for our project.

## Specifications

- Provider    : EasyCaching.HybridCache (1.6.1)
- Interceptor : AspectCore (6.0.0)

### PR DESCRIPTION
**Pull request by xsoheilalizadeh**
Fixes #399 

Only Memcached is not supported among the providers, if you have any ideas on how we can implement it I'd like to hear them.

### CODE REVIEW

**Comment by catcherwong** [comment]
> Only Memcached is not supported among the providers, if you have any ideas on how we can implement it I'd like to hear them.

I don't have a good idea about Memcached as well. **NotSupportedException** is fine.

**Comment by xsoheilalizadeh** [comment]
Hi @catcherwong, did you have time to look into the PR?

**Comment by catcherwong** [comment]
@xsoheilalizadeh  In the last review, I pointed out some problems, you should fix them. 😄

**Review by catcherwong — CHANGES_REQUESTED** [review]

**Comment by xsoheilalizadeh** [comment]
Thanks @catcherwong, I addressed the requested changes. 

P.S: I am not sure which last review you mean because I didn't receive any reviews until 2 days ago.

**Review by catcherwong — APPROVED** [review]
LGTM

**Comment by timschwallie** [comment]
For memcached would probably need to maintain a key of keys, aka allKeys.
Then on pattern removal, grab all the keys and run through them for pattern match.
At the same time, you may need to implement a locking mechanism.
Parallel.ForEach might be a way to speed it up using multiple threads.
Keys in 'allKeys' may not exist because of evictions.

To make it consistent, you would need to move this pattern to the other Caches.
Slows things down a touch on create, removals, etc.

Note, this does begin to lead into being able to support dependent Keys.

**Pull request merged**
