### PR TITLE
Update dependencies to the latest version

### PR DESCRIPTION
**Pull request by mjebrahimi**
Update dependencies to the latest version **except for CSRedis because has break changes**.

### CODE REVIEW

**Comment by mjebrahimi** [comment]
Updating CSRedis can be challenging because of this [break change](https://github.com/2881099/csredis/releases/tag/v3.3.0)
It replaces double with decimal for all of all relevant API

We have two options:
1. Changing double to decimal in [IRedisCachingProvider](https://github.com/dotnetcore/EasyCaching/blob/master/src/EasyCaching.Core/IRedisCachingProvider.cs) which takes more effort (also need to changing SERedis impl) and leads to break changes
2. Taking the same double as before and converting it to decimal before sending it to CSRedis API (**I prefer**)

**Comment by catcherwong** [comment]
@mjebrahimi  LGTM, But you should change the target branch from `master` to `dev`!

**Comment by mjebrahimi** [comment]
Sorry my friend, I didn't know.
I did it now. Please check if it is OK?
#205

**Comment by catcherwong** [comment]
#205 merged.

**Pull request closed without merging**
