### PR TITLE
Allow to cache nulls

### PR DESCRIPTION
**Pull request by Youkai-no-nii-chan**
https://github.com/dotnetcore/EasyCaching/issues/222

### CODE REVIEW

**Comment by Youkai-no-nii-chan** [comment]
Only two flacky unrelated tests failed. Not sure is it worth to fix them in this PR.

**Comment by catcherwong** [comment]
Thanks, I will take a look ASAP.

**Review by catcherwong — COMMENTED** [review]
LGTM

**Comment by catcherwong** [comment]
Could you please change the target branch from `master` to `dev`?

**Comment by Youkai-no-nii-chan** [comment]
> Could you please change the target branch from `master` to `dev`?

Done

**Review by catcherwong — APPROVED** [review]

**Comment by catcherwong** [comment]
Release version 1.1.0-alpha20201001103202 for this PR.

If there is no feedback in the near future, we will release a stable version. Thank you very much!! 😄

**Pull request merged**
